In [4]:
from importlib.metadata import version

print(version("torch"))
print(version("tiktoken"))

2.13.0
0.13.0


In [5]:
import os
import requests

file_path = "the-verdict.txt"

if not os.path.exists("the-verdict.txt"):
    url = ("https://raw.githubusercontent.com/rasbt/"
        "LLMs-from-scratch/main/ch02/01_main-chapter-code/"
        "the-verdict.txt")

    file_path = "the-verdict.txt"

    response = requests.get(url, timeout=30)
    response.raise_for_status()
    with open(file_path, "wb") as f:
        f.write(response.content)


In [6]:
with open(file_path, "r", encoding="utf-8") as f:
    raw_text = f.read()

print(len(raw_text))
print(raw_text[:99])

20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [7]:
import re

text = "Hello, World. This, is a test."
result = re.split(r'([,.]|\s)', text)

print(result)

['Hello', ',', '', ' ', 'World', '.', '', ' ', 'This', ',', '', ' ', 'is', ' ', 'a', ' ', 'test', '.', '']


In [8]:
result = [item for item in result if item.strip() != '']

print(result)

['Hello', ',', 'World', '.', 'This', ',', 'is', 'a', 'test', '.']


In [9]:
text = "Hello, world. Is this-- a test?"

result = re.split(r'([,.!;/?]|--|\s)', text)
result = [item for item in result if item.strip()]

print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


In [10]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]

print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [11]:
print(len(preprocessed))

4690


In [12]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)

print(vocab_size)

1130


In [13]:
vocab = {token:integer for integer,token in enumerate(all_words)}

In [14]:
for i,item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


In [48]:
import sys
import os

# Ativa o recarregamento automático
%reload_ext autoreload
%autoreload 2

# Calcula o caminho da raiz do projeto (um nível acima da pasta atual)
caminho_raiz = os.path.abspath('..')

# Adiciona a raiz aos caminhos que o Python reconhece, se já não estiver lá
if caminho_raiz not in sys.path:
    sys.path.append(caminho_raiz)

# Faz o import normal
from classes_functions.tokenizer import SimpleTokenizerV1

tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""

ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [20]:
tokenizer.decode(ids)

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [21]:
tokenizer.decode(tokenizer.encode(text))

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [22]:
all_tokens = sorted(set(preprocessed))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

In [23]:
print(len(vocab))

1132


In [27]:
for i,item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [ ]:
import sys
import os

# Ativa o recarregamento automático
%reload_ext autoreload
%autoreload 2

# Calcula o caminho da raiz do projeto (um nível acima da pasta atual)
caminho_raiz = os.path.abspath('..')

# Adiciona a raiz aos caminhos que o Python reconhece, se já não estiver lá
if caminho_raiz not in sys.path:
    sys.path.append(caminho_raiz)

# Faz o import normal
from classes_functions.tokenizer import SimpleTokenizerV2

tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [33]:
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]

In [34]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

In [35]:
import importlib
import tiktoken

print("tiktoken version:", importlib.metadata.version("tiktoken"))

tiktoken version: 0.13.0


In [37]:
tokenizer = tiktoken.get_encoding("gpt2")

In [ ]:
text = (
 "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace.")

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [39]:
string = tokenizer.decode(integers)

print(string)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [40]:
with open("the-verdict.txt", 'r', encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)

print(len(enc_text))

5145


In [41]:
enc_sample = enc_text[50:]

In [42]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size + 1]

print(x)
print(y)

[290, 4920, 2241, 287]
[4920, 2241, 287, 257]


In [44]:
for i in range(1, context_size + 1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(f"{context} ---> {desired}")


[290] ---> 4920
[290, 4920] ---> 2241
[290, 4920, 2241] ---> 287
[290, 4920, 2241, 287] ---> 257


In [46]:
for i in range(1, context_size + 1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(f"{tokenizer.decode(context)} ---> {tokenizer.decode([desired])}")

 and --->  established
 and established --->  himself
 and established himself --->  in
 and established himself in --->  a


In [49]:
with open("the-verdict.txt", 'r', encoding="utf-8") as f:
    raw_text = f.read()

In [57]:
import sys
import os

# Ativa o recarregamento automático
%reload_ext autoreload
%autoreload 2

# Calcula o caminho da raiz do projeto (um nível acima da pasta atual)
caminho_raiz = os.path.abspath('..')

# Adiciona a raiz aos caminhos que o Python reconhece, se já não estiver lá
if caminho_raiz not in sys.path:
    sys.path.append(caminho_raiz)

# Faz o import normal
from classes_functions.dataloader import create_dataloader_v1

dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [58]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [60]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs: \n", inputs)
print("Targets: \n", targets)

Inputs: 
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Targets: 
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [62]:
import torch

vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [61]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)


Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [65]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

print(token_embeddings)

torch.Size([8, 4, 256])
tensor([[[-1.5034,  0.1658, -1.7090,  ..., -0.0167,  0.0880, -0.1819],
         [-0.1265,  1.0145, -0.0984,  ...,  0.6896, -0.0882,  0.6804],
         [ 0.2088, -1.0313,  2.7477,  ..., -0.6615, -0.2069,  0.3520],
         [ 0.1346, -0.3260, -1.6713,  ...,  0.3580, -1.4882,  1.1179]],

        [[-0.1980, -0.8296, -0.1664,  ..., -0.4426, -0.7032,  0.3330],
         [ 0.5452,  0.0414,  0.3633,  ..., -0.8330, -0.8725, -0.0453],
         [-0.8905, -0.1349,  0.1640,  ..., -0.7422, -0.2093,  0.1722],
         [ 1.1202, -0.8517,  0.4458,  ..., -1.2680, -0.9033,  0.2035]],

        [[-1.8844, -1.0277,  1.2689,  ..., -1.2539,  1.2673, -3.0356],
         [ 0.7683,  1.1327,  0.6276,  ..., -1.0327,  0.1585, -0.1133],
         [-0.1227, -0.6953,  0.0321,  ..., -0.6804,  0.7528,  1.1550],
         [ 0.3051,  1.7908,  0.9247,  ...,  0.2686,  1.4853, -0.2264]],

        ...,

        [[ 1.6549, -1.7824,  1.5922,  ...,  3.1575,  0.7495, -1.9384],
         [ 0.3816,  1.4303, -0.25

In [70]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

print(pos_embedding_layer.weight)

Parameter containing:
tensor([[-1.6827,  1.0657,  0.3731,  ..., -1.1107, -0.5474, -0.2097],
        [-0.8373,  0.6617,  0.8769,  ..., -0.3725, -0.6470, -2.1685],
        [ 0.1352, -0.2682, -0.0660,  ..., -0.4829, -1.4115, -0.4091],
        [ 1.4810, -0.5930, -0.6335,  ...,  0.7744, -1.2900,  1.1096]],
       requires_grad=True)


In [71]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))

print(pos_embeddings.shape)

torch.Size([4, 256])


In [72]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
